name: YouTube to Podcast

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache Python packages
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp pydub feedgen google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run script
        run: python main.py
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Commit and push RSS feed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add podcast.xml
          git commit -m 'Update podcast feed'
          git push origin main
