name: YouTube to Podcast

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache Python packages
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache ffmpeg directory
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: /usr/local
          key: ${{ runner.os }}-ffmpeg
          restore-keys: |
            ${{ runner.os }}-ffmpeg

      - name: Install ffmpeg if not cached
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp pydub feedgen

      - name: Run script
        run: python main.py

      - name: Temporarily disable .gitignore
        run: |
          echo "audio/\n!audio/*.mp3\npodcast.xml\n!podcast.xml" > .git/info/exclude

      - name: Commit and push RSS feed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add audio/*.mp3 podcast.xml
          git commit -m 'Update podcast feed with new episodes and audio files' || echo "No changes to commit"
          git push origin main

      - name: Revert .gitignore changes
        run: |
          rm .git/info/exclude
